services:
  - type: web
    name: felicity-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false          # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false          # set manually in Render dashboard
      - key: FRONTEND_URL
        sync: false          # set to your Vercel URL after deploying frontend
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false          # set manually in Render dashboard
      - key: SMTP_PASS
        sync: false          # set manually in Render dashboard
      - key: SMTP_FROM
        sync: false          # e.g.  "Felicity Events" <you@gmail.com>
